### PR TITLE
Improve websearch

### PR DESCRIPTION
**Pull request by AlanDrake**
This PR implements case-insensitive search by default and highlighting, to address a few cons from #57.

Case-insensitive search works by building another lookup table and forcing lowercase lookups, but the search function has been upgraded with an extra `is_case_sensitive` parameter in case someone wants to add a checkbox to toggle  case sensitivity.

For better search third party services are required, like Algolia, or other self hosted solutions. A pure static site can only do so much.

### CODE REVIEW

**Comment by morganwillcock** [comment]
It is a little late now, but the idea of the vendor directory was to keep code third party code separate from the other directories. e.g. normalize.css is copied from the vendor directory and not from the css directory

**Comment by ericoporto** [comment]
sorry morgan, I didn't realize this was the directory intention. Can you adjust this in master directly?

**Comment by ericoporto** [comment]
ok, I think I fixed here: https://github.com/adventuregamestudio/ags-manual/commit/e28c1b2818226d1018a910b7db37dc73d4abbaf9

**Comment by ericoporto** [comment]
ok, I the artifacts are identical and I can't figure this out, I have checked in MacOS.

**Comment by AlanDrake** [comment]
My apologies for not using the vendor folder

**Comment by morganwillcock** [comment]
It is no big deal, just that it then doesn't make sense to have the other parts separate. 

I'm pretty sure the diff comparison failing will have been because of line ending conversion when the code is checked out. I'll take a look.

**Comment by ericoporto** [comment]
If that's the case, please also update the git attributes for this:

https://github.com/adventuregamestudio/ags-manual/blob/master/.gitattributes

**Comment by morganwillcock** [comment]
It isn't that easy to globally define the line endings because anything read as a template has its line endings ignored by Pandoc on input and set by Pandoc on output, and that is source code that is editable not something that should be preserved regardless of platform.

It should be OK to set wildcard matches for anything within the vendor directory since those files probably shouldn't be manually edited (really it just avoids using a package manager and an Internet connection).

**Pull request merged**
