### PR TITLE
adds toggable dark/light mode

### PR DESCRIPTION
**Pull request by ericoporto**
this PR adds a toggle for light and dark mode in the web version of the manual:

http://ericoporto.github.io/ags-manual

If you have loaded it before, use Ctrl+Shift+R or whatever your browser's empty cache and reload shortcut is to remove previous builds of it from your cache.

fixes over PR #140 

Edit: updated the build in my branch too.

### CODE REVIEW

**Comment by morganwillcock** [comment]
I still see the switch move to the left on every page load, but I guess that isn't a big deal and might be fixable later.

I've quickly scrolled through every page on both themes and I didn't see any obvious problems. The only thing I did notice was that the footer text was no longer dimmed compare to everything else, but that isn't really a big deal either.

Comparing it to mine, I thought that the light theme worked better with a lighter (thinner) font and higher contrast, but how much of that is dependent on my monitor settings I'm not sure. Maybe @selmiak will know a good way to judge the contrast.

Here is the PR:
yours

Here is mine:
mine

**Comment by ericoporto** [comment]
I did small adjustments 
- footer now uses the correct color
- h1, h2, and h3 is lighter
- background is slightly clearer

The button transition prevention on load though, my guess is it's a bug in Firefox, I don't understand why it's not preferring the `!important` tag on my css - it appears to work on other browsers. :/

**Comment by morganwillcock** [comment]
The last issue that I can find is that the local storage data is always created when visiting the page, storing the current preference of `prefer-color-scheme` or the default theme. This effectively bypasses the use the system/browser wide preference after the first page visit. I think it should only write the preference as local data if the user interacted with the switch. In this way the user can choose to rely on the global preference if they switch between the light and dark mode on the same machine, which is likely on a laptop when moving between different lighting conditions.

**Comment by ericoporto** [comment]
Ah, yes, that is easy to fix, I will change that tomorrow. :)

**Comment by ericoporto** [comment]
Erh, tomorrow took a bit longer, but change is done!

**Pull request merged**
