### PR TITLE
Test build with m2r and inserted index directives

### PR DESCRIPTION
**Pull request by morganwillcock**
This should hopefully build with:
- a correct main contents page for CHM and web pages
- automatic index based on H2 and H3 headers
    - `##` for a single index directive
    - `###` for a pair of index directives (## --> ### and ### --> ##)
    - source will require some editing but temporary part of the scripts are making some changes to test without the wiki being changed
- inserted local TOC in CHM pages (HTML is slightly broken, but render okay)
- link to genindex.html (equivalent of CHM index) for the web pages

### CODE REVIEW

**Comment by morganwillcock** [comment]
@ericoporto do you know if there is any easy way to get the build artifacts?

**Comment by ericoporto** [comment]
[pr_output.txt](https://github.com/adventuregamestudio/ags-manual/files/2260461/pr_output.txt)
[build_html.zip](https://github.com/adventuregamestudio/ags-manual/files/2260463/build_html.zip)
[AGSHelpdoc.chm.zip](https://github.com/adventuregamestudio/ags-manual/files/2260464/AGSHelpdoc.chm.zip)

@morganwillcock it's possible to create a way to upload artifacts from **pull requests** from the same repository. It's not possible to upload artifacts from **pull requests** from external forks of the repository since this would cause the external person to have access to the Github Token of @ags-manual-ci .

**Comment by morganwillcock** [comment]
I've just pushed a fixed version (needed to escape some backslashes again). That should fix the front page, which is the only one generated by manually parsing the file - the alternative would be to add rst directives to Home.md, but then it wouldn't be pure markdown any more and it would look weird on the GitHub wiki. CHM file complicates things here, as the TOC is mapped directly onto the contents page in the help viewer.

A lot of the warnings are from problems on the source side, or rather that when scanning for things to index there are H3 headers with no H2 headers before them, and since I'm modifying the files in-place it is tricky to track previous content. At the moment I'm only modifying a single page to fix that, just to see how the indexing was working, but if it needed to work better it would probably be easier to write new copies of the file out rather than modify the source files (buffering in sed probably wouldn't be enough).

**Comment by ericoporto** [comment]
[pr_output.txt](https://github.com/adventuregamestudio/ags-manual/files/2260509/pr_output.txt)
[AGSHelpdoc.chm.zip](https://github.com/adventuregamestudio/ags-manual/files/2260510/AGSHelpdoc.chm.zip)
[build_html.zip](https://github.com/adventuregamestudio/ags-manual/files/2260511/build_html.zip)

image
Everything appears to be working correctly now!

**Comment by ericoporto** [comment]
I have a problem I can't explain... I can read the generated `AGSHelpdoc.chm` using `wine hh AGSHelpdoc.chm`, from [releases](https://github.com/adventuregamestudio/ags-manual/releases/tag/0.1.2), but I can't read it using the default Windows 10 viewer for helpfiles. So something is broken on the `chm` file.

**Comment by ivan-mogilko** [comment]
> I can't read it using the default Windows 10 viewer for helpfiles

What is this viewer program exactly, is it suppose to open CHMs? Can you open ags-help.chm from existing editor releases?

**Comment by morganwillcock** [comment]
If you download it on Windows, you'll probably have to remove the SecurityZone data from it, i.e. go to file properties and 'unblock' the file. I'm on Windows 10 and it seems okay.

**Comment by ericoporto** [comment]
image

@morganwillcock you were right! It's weird that the file actually opens before I do that, but is blank.

image

but after marking the unblock checkbox, it works. I did not just blanked the image on paint, both are the actuall alt+printscreen.

image

I just found it weird because the version I built on my own computer worked, but the version from TravisCI had this weird problem. I think I didn't noticed it before - maybe I hadn't boot Windows before, but I can't really remember.

@ivan-mogilko below is the software I use on Windows 10 for viewing chm files. I don't remember installing anything, so I would guess it either comes with Windows or came with another software I installed.

image

**Comment by ivan-mogilko** [comment]
@ericoporto , this was a known problem, it happens to some users with our old help too when they download editor in a zip archive.

**Pull request merged**
