### PR TITLE
Add logo and some color

### PR DESCRIPTION
**Pull request by morganwillcock**
Test build for including a logo and some custom CSS.

- The logo is just the [favicon from the website](http://adventuregamestudio.co.uk/favicon.ico) (presumably this is okay to use?), but scaled up
- CSS override aligns the logo to the left
- Theme option sets the color for the sidebar headings
- Template override is to remove the link from the TOC heading, so that it gets the correct color (the logo is linking to the same location anyway)

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
I now remembered that @ericoporto was asking about "cup with teabag" logo from the old splash screen some time ago. I believe these may be got from user **abstauber** who had original photoshop documents with these.

Also, these were previously suggested as alternate AGS icons: 
this one was by CaesarCub:
https://i.imgur.com/NpAZxPJ.png
these are also by abstauber:
http://shatten.sonores.de/wp-content/uploads/2018/06/1ags256.png
http://shatten.sonores.de/wp-content/uploads/2018/06/ags_classic_cup.png

**Comment by ericoporto** [comment]
I merged! I liked the scaled icon @morganwillcock used, so I re positioned it to look a little better - in my opinion. I think later the icon should be what is on AGS 3.5.0. I also added a favicon because made sense with the current update.

**Comment by ivan-mogilko** [comment]
> I'm not sure if anyone ever noted it, but this one is a big white cup, not a big blue cup.

We have a white cup on current editor's splash screen too ;).

**Comment by tzachshabtay** [comment]
White is the new blue!

**Comment by ericoporto** [comment]
We an icon on the organization on github! Maybe the drink milk cup is it?

**Pull request merged**
