### PR TITLE
adds info on how to contribute to the docs

### PR DESCRIPTION
**Pull request by ericoporto**
- mention screenshots and how it has to be added through git
- general how the sausage is made information

@morganwillcock  I wrote this long ago but then I didn't add (for some reason), but I just remembered today when I noticed we didn't had screenshots for the templates...

Last time you asked me to include information on the headers and format, but I don't remember how it works, I think only h1 and h2 gets indexed, and I believe you would comment something on using code tags and the index of script api, but since you are more familiar with the implementation details I would prefer you would write it. Also you have better English skills 😬 

Also opening again because the web interface made me create the branch in the wrong place.

### CODE REVIEW

**Comment by morganwillcock** [comment]
Possibly some of the specifics need checking:

> Screenshots should be saved as PNG or JPG, with a width of at least 400 px.

Maybe it is best to prefer PNG in all cases to remain consistent, but possibly that depends on a maximum size that we specify for the width. In practice I think the issue would be that people add images which are too large rather than too small, and a maximum width for the image needs to align well with the break point and maximum width that is specified for the container in CSS.

> Try to keep the file size less than 220KB.

I was wondering where this number comes from.

> Finally, the actual inclusion of screenshots in the manual can only be done by people with commit access to the repository wiki, likely the docs-contributors team.

I've never actually tested it but I presumed that anyone with a GitHub account can checkout the wiki contents and push the commits directly back, so anyone with an account can create image files. Are public edits actually only possible through GitHub's web based editor?

**Comment by ericoporto** [comment]
> I've never actually tested it but I presumed that anyone with a GitHub account can checkout the wiki contents and push the commits directly back, so anyone with an account can create image files. Are public edits actually only possible through GitHub's web based editor?

So there is no information at all in the [official GitHub docs.](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) I made an experiment just now,  I created a new user account but I kept getting 403 when pushing.

```
remote: Permission to adventuregamestudio/ags-manual.wiki.git denied to eri0o.
fatal: unable to access 'https://github.com/adventuregamestudio/ags-manual.wiki.git/': The requested URL returned error: 403
```

> > Try to keep the file size less than 220KB.

> I was wondering where this number comes from.

Number is arbitrary, taken from looking other similar guidelines, we can change it.

> > Screenshots should be saved as PNG or JPG, with a width of at least 400 px.

> Maybe it is best to prefer PNG in all cases to remain consistent, but possibly that depends on a maximum size that we specify for the width. In practice I think the issue would be that people add images which are too large rather than too small, and a maximum width for the image needs to align well with the break point and maximum width that is specified for the container in CSS.

I think yeah, we could make new images only png, this is probably best. On the width max size, I think in the web it will get adjusted however it's specified, or if not we can make a CSS rule so it is. But I don't have a number for max size, but it could be any arbitrary one we invent right now. Like, maybe 1024 px ?

**Comment by ericoporto** [comment]
Hey, I would like to add info on headers but I don't remember it...

**Comment by morganwillcock** [comment]
Any inline code within a heading will trigger two metadata changes:

1. The heading is flagged as describing the script API instead of being a regular manual page
2. The index name for the heading is set to the text that was within the inline the code element rather than the text for the heading element

It is probably easier to see by example:

```
$ echo '## `Viewport` functions and properties' | pandoc --from gfm --to lua/write_metablock.lua
-- nil

return {
  ["links"] = {
  },
  ["keywords"] = {
    ["properties"] = 1,
    ["functions"] = 1,
    ["Viewport"] = 1,
  },
  ["index"] = {
    [1] = {
      ["itemtype"] = "script",
      ["id"] = "viewport-functions-and-properties",
      ["header"] = "Viewport",
    },
  },
}

$ echo '## Function definitions for `Viewport`' | pandoc --from gfm --to lua/write_metablock.lua
-- nil

return {
  ["links"] = {
  },
  ["keywords"] = {
    ["definitions"] = 1,
    ["Viewport"] = 1,
    ["Function"] = 1,
  },
  ["index"] = {
    [1] = {
      ["itemtype"] = "script",
      ["id"] = "function-definitions-for-viewport",
      ["header"] = "Viewport",
    },
  },
}

$ echo '## Viewports and why they are cool' | pandoc --from gfm --to lua/write_metablock.lua 
-- nil

return {
  ["links"] = {
  },
  ["keywords"] = {
    ["why"] = 1,
    ["cool"] = 1,
    ["Viewports"] = 1,
  },
  ["index"] = {
    [1] = {
      ["itemtype"] = "editorial",
      ["id"] = "viewports-and-why-they-are-cool",
      ["header"] = "Viewports and why they are cool",
    },
  },
}
```

**Comment by ericoporto** [comment]
Hey, is it possible to restrict this to pages linked from the script API? I had to document the plugin API and thought they made sense as inline code...

**Comment by morganwillcock** [comment]
> Hey, is it possible to restrict this to pages linked from the script API?

The process is what is actually determines whether content is related to the script API, so that isn't known in advance. It means that the commands show up in the top level of the index instead of being part of a sub-list, but as long as you don't cause a collision with an existing script keyword or (non-script API) page title it isn't necessarily a problem.

**Comment by ivan-mogilko** [comment]
Sorry to bump this, but this is open for about a month, is it okay to merge?

**Pull request merged**
