### PR TITLE
adds toggable dark/light mode

### PR DESCRIPTION
**Pull request by ericoporto**
this PR adds a toggle for light and dark mode in the web version of the manual:

http://ericoporto.github.io/ags-manual

If you have loaded it before, use Ctrl+Shift+R or whatever your browser's empty cache and reload shortcut is to remove previous builds of it from your cache.

I am making a draft PR since I think there are still things to fix in the theme, but I would like to get input on it's look and feel.

### CODE REVIEW

**Comment by selmiak** [comment]
maybe a tooltip for the toggle helps.

https://ericoporto.github.io/ags-manual/FAQ.html
scroll down, some black text stays black on both versions, which is not good for the dark mode of course.
Seems to be list elements.

**Comment by morganwillcock** [comment]
I had been trying the same thing, although just with CSS. I think I had checked the colors. Maybe we can glue both of our attempts together.

https://github.com/morganwillcock/ags-manual/commit/25010ea7c83e9948f03aaaac725ee10298a7b884

**Comment by ericoporto** [comment]
Thanks! Will leverage your colors. I wanted to use a button since I don't know how to switch system wide dark/light settings on my distro. I use JS since I needed to store the settings so it could be read from other pages.

I discovered you can't dynamically change the colors of the bullets in lists apparently, am trying to figure out that still.

I added a bit css magic there too because I wanted the button a little prettier, I thought it fit alright with the page. I briefly wanted to add one of those with a sun and a moon but couldn't figure out how to it neatly. :/

**Comment by ericoporto** [comment]
Hey, I updated the build in my website (https://ericoporto.github.io/ags-manual/), use Ctrl+Shif+R to do a hard reload of it to check, you will get a smooth transition between dark and light mode. I switched my light mode colors for @morganwillcock . I haven't been able to figure a tooltip (as suggested by @selmiak ) that looks ok though. 

I also think I got all the theme fixed, please test.

**Comment by morganwillcock** [comment]
With the dark mode turned on it seems that every page default to being light when it loads and then switches to dark mode (it looks a lot like the screen is flashing white on every page load). Do you see the same thing? I'm testing in Firefox 89.

**Comment by ericoporto** [comment]
it's possibly because the script is loaded after the HTML instead of before (on body instead of on header). Any particular reason why the script is on body? I could move the JS code to a separate js file just for the toggle.

**Comment by morganwillcock** [comment]
> it's possibly because the script is loaded after the HTML instead of before (on body instead of on header). Any particular reason why the script is on body?

I think because the JSON search data is quite large so it let the page render without waiting for that.

> I could move the JS code to a separate js file just for the toggle.
> 
> Edit: erh, tried to add a line in the GNUmakefile for copying js files but it does nothing.
> 
> ```
> $(eval $(call CP_template,html/js/%.js,html/build/js/%.js))
> ```
> 
> @morganwillcock I separated said file below, but I don't know how to move it into the build process. Also, I would like to not have that license in it, but since you had a license in the other js file I kept it. I tested by using throttling locally and it appears to fix or reduce the flashing.

It should copy if you add the eval line and also add it as a dependency on the html target: https://github.com/ericoporto/ags-manual/blob/feature-dark-light-toggle/GNUmakefile#L69-L71

**Comment by ericoporto** [comment]
@morganwillcock I did that, and it appeared to work (locally), but somehow broke a checksum match.

**Comment by morganwillcock** [comment]
> @morganwillcock I did that, and it appeared to work (locally), but somehow broke a checksum match.

The mismatch is probably because of line ending conversion, so anything is cloned and copied is potentially an error if the built result is meant to be identical on all platforms. You can fix it by specifying the line endings to use instead of using the automatic conversion, I already had to do it for some other files. You can probably just add this to .gitattributes:

```
html/js/* eol=lf
``` 
 
> It still built and published at [gh-pages](https://ericoporto.github.io/ags-manual/) though, so maybe test if it works for you.

I think the flashing is gone, although I still see the toggle switch move. I will test it more later. There is some potential for weirdness based on how browsers treat local storage usage in certains scenarios (I think in private browsing windows in particular and it would be bad if the theme reverted on every click), plus we need to check the fallback behaviour when Javascript is turned off (that all defaults are still from one theme and not a mix of the two).

**Comment by ericoporto** [comment]
Local Storage is shared to all tabs in private mode in Chrome and Firefox as far as I know, if the pages are in the same domain. Note that the first time it loads it uses the preferred OS theme.

If JS is turned off it will default to the light theme (body won't have dark theme class).

The toggle switch move is easy to fix with JS, I can just attach it's transition css parameters after it switched.

**Pull request closed without merging**
