### PR TITLE
Switch from Sphinx to Pandoc

### PR DESCRIPTION
**Pull request by morganwillcock**
- [x] CI build for CHM file
- [x] CI build for website
- [x] website index page
- [x] website search
- [x] website CSS

This switches from building with Sphinx to building with Pandoc:
- fixes internal documents links which were broken by conversion through reST
- cleaner HTML and CSS for CHM build
- scripting runs using the Lua interpreter that is built into Pandoc (no dependency on Python)

This serves as a basic starting point, which is mostly equivalent to what the Sphinx website build is doing. In terms of layout, style, and search functionality it is the bare minimum that was easily portable for build purposes, but components are not tangled enough to cause a problem with replacing parts with something else.

Note:
- search is currently case sensitive (wouldn't be too hard to make it insensitive) and pre-calculated in hash tables (so there is no actual search, only key lookups and adding the score)
- search data is not minified, but I think it would drop in size by about 200k if it was
- search highlight words are passed in the result URL, but there is no script present for highlighting

### CODE REVIEW

**Comment by ericoporto** [comment]
I would remove [this line from the README](https://github.com/adventuregamestudio/ags-manual/pull/43/commits/aa51e06d3f263b7bad339787c8d37a85ca592f9f#diff-04c6e90faac2675aa89e2176d2eec7d8R83). Pandoc should be `/usr/bin/pandoc` on debian based Linux distros. Instead it's better to state in the text before something like:
> if make can't find your `pandoc` install, set `PANDOC` variable to your installed `pandoc` binary.

**Comment by ericoporto** [comment]
[travis.yml.zip](https://github.com/adventuregamestudio/ags-manual/files/2947893/travis.yml.zip) | [Dockerfile.zip](https://github.com/adventuregamestudio/ags-manual/files/2947886/Dockerfile.zip) | [hub.docker.com/r/ericoporto/ags-manual](https://hub.docker.com/r/ericoporto/ags-manual)

If the necessity ever arrive to use a docker for the manual something like that could work - if pandoc latest doesn't work on travis or we decide to switch to circle-ci.

**Comment by ericoporto** [comment]
Hey! I did some testing and couldn't find any problems, is there some know problem or can we merge this?

**Comment by morganwillcock** [comment]
> Hey! I did some testing and couldn't find any problems, is there some know problem or can we merge this?

The only problem I can find is something that looks like an internal Pandoc issue, where list elements that incorporate a block are mistakenly wrapped in a paragraph, but I think this only happens on the credits page.

But overall, I think it is working well enough to switch. If you ignore the website part, the CHM build is significantly better because we've now got full control over the templating, which is probably reason enough.

**Comment by ericoporto** [comment]
Ok, I was able to find the problem you mentioned:

https://ericoporto.github.io/public_html/build/SystemLimits.html

https://adventuregamestudio.github.io/ags-manual/SystemLimits.html

I think this is very minimal so I will just merge!

**Pull request merged**
