### PR TITLE
Add Lua filter for dynamic TOC insert in htmlhelp pages

### LINKED ISSUE #119: Restore TOC links in CHM pages
The TOC links (what shows in the left hand 'frame' of the web site build) should be shown at the top of each CHM page so that if you are at the top you can jump to lower positions in the page using anchor links. The data is already within Pandoc as it is stored as a 'ready to render' TOC for the page, but unfortunately there is no option to shift the headings levels within the TOC, so it is always forced to begin at the first level, and the first level is the page title, so there is heading duplication and a lack of flexibility.

There are likely three ways to add the TOC with a custom starting position:
1. Use the existing global header shift option with a negative shift + a custom filter that implements a positive shift + template changes + heading level changes on the markdown files
2. Look to patch Pandoc to implement a TOC shift in the same way that it already has an option for the global header shift
3. Ignore the built in TOC feature and write a replacement TOC generator based on the page metadata that is already stored using a custom filter or writer

Option 1 isn't too hard to do (I already did it as a test) but it makes a mess of the template structure.

Option 2 would depend on someone writing a patch and it being accepted into Pandoc (I am speaking to someone about how feasible it is as a contracted job, or possibly I will try myself, or possibly a Haskell expert will stumble across this text and decide it is worthwhile).

Option 3 should be feasible, but is really just a poor man's option 2. It is likely preferable to option 1.

### PR DESCRIPTION
**Pull request by morganwillcock**
TOC will possibly be inserted above or below the first page heading depending on:

 - whether a later heading has the same level as the first
 - the total number of headings

TOC depth is loosely tracked against the actual heading depth, which should look reasonable where heading levels do not attempt a negative shift (if the page structure looks OK then likely the TOC will look OK too).

Raises minimum Pandoc version required to 2.9.2 since this is where pandoc.List gained the insert method.

Fixes #119

### CODE REVIEW

**Comment by ericoporto** [comment]
@morganwillcock the build here didn't fail, so the removed hooks are really gone.

**Comment by morganwillcock** [comment]
Yes, I think it will be OK from this point onwards. I'll merge this in a couple of days unless anyone says otherwise, and probably make a release after some minor page edits.

**Comment by ericoporto** [comment]
image

Just in case anyone wants to see how things works now, on top of this page there is an Action tab, and clicking there you can check the builds and reach the artifacts - which is pretty sweet. Also, as top image shows, the table of contents are in the HTML help file now!

**Comment by ivan-mogilko** [comment]
Hmm, I missed most of what is going on here, but it's very nice to see the local TOC back.

> Would probably be useful to merge this soon in case 3.5.0 gets a newer release

Actually, yes, I was recently doing another hotfix, but did not set a release yet, so there's a chance to include this.

**Pull request merged**
